INSERT INTO "City"(
            id, name_city, id_country)
    VALUES (21, 'Canberra', 6),
           (22, 'Sydney', 6),
           (23, 'Darwin', 6),
           (24, 'Palmerstone', 6),
           (25, 'Brisbane', 6),
           (26, 'Adelaide', 6),
           (27, 'Whyalla', 6),
           (28, 'Hobart', 6),
           (29, 'Melbourne', 6),
           (30, 'Perth', 6),
           (31, 'Cairns', 6),
           (32, 'Newcastle', 6),
           (33, 'Wollongong', 6),
           (34, 'Townville', 6),
           (35, 'Bendigo', 6),
           (36, 'Geelong', 6),
           (37, 'Ballarat', 6),
           (38, 'Albury', 6),
           (39, 'Wodonga', 6),
           (40, 'Mackay' , 6);